PUT http://localhost:3003/api/blogs/6242cf6de37f75c66c6b19c9
Content-Type: application/json

{
  "title": "Buratino",
  "author": "Aleksey Tolstoi",
  "url": "wwwleningradwww.ru",
  "likes": 777
}




